"""Create runs tools and deliveries journal"""

import sqlalchemy as sa
from alembic import op

revision = "ad077c7f4012"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "check_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("app_mode", sa.String(length=20), nullable=False),
        sa.Column("chat_id", sa.String(length=30), nullable=False),
        sa.Column("trigger", sa.String(length=30), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("period", sa.JSON(), nullable=False),
        sa.Column("client_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("reports", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("report_text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_check_runs_app_mode"), "check_runs", ["app_mode"], unique=False)
    op.create_index(op.f("ix_check_runs_chat_id"), "check_runs", ["chat_id"], unique=False)
    op.create_table(
        "deliveries",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("next_part", sa.Integer(), nullable=False),
        sa.Column("parts", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "tool_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("app_mode", sa.String(length=20), nullable=False),
        sa.Column("chat_id", sa.String(length=30), nullable=False),
        sa.Column("tool", sa.String(length=80), nullable=False),
        sa.Column("client_id", sa.String(length=32), nullable=True),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error", sa.String(length=120), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_events_request_id"), "tool_events", ["request_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_events_request_id"), table_name="tool_events")
    op.drop_table("tool_events")
    op.drop_table("deliveries")
    op.drop_index(op.f("ix_check_runs_chat_id"), table_name="check_runs")
    op.drop_index(op.f("ix_check_runs_app_mode"), table_name="check_runs")
    op.drop_table("check_runs")
    # ### end Alembic commands ###
